import Footer from '@/components/footer/Footer';
import './globals.css';
import { Poppins } from 'next/font/google';
import Navbar from '@/components/navbar/Navbar';

const inter = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'] 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
          <Navbar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  )
}
